"""
An input to the RobotModel generated by a controller.
This most likely is just the velocities of the left and right motors.
"""


class RobotModelInput:

    # units in linear inches per second
    def __init__(self, leftVelocity: float, rightVelocity: float):
        self.leftVelocity = leftVelocity
        self.rightVelocity = rightVelocity